### ISSUE TITLE
Entwurf (!) für das einfachste AirShopping NDC transaction setup mit XapiX

### ISSUE THREAD

**Issue by pickledolives** [xapix-io/xapix_ndc_client#1]
Folgendes ist von mir noch vorbereitend zu erledigen:

- In XapiX die "air_shopping_responses" Resourcen anlegen, ähnlich wie wir es gestern für "air_shopping_requests" gemacht haben
- In XapiX implementiere ich das Feature mit einem POST auf einen Output Endpoint ein AWS Lambda zu triggern. Keeps it simple, hält Verarbeitungslogik aus meiner Platform heraus, etablierter und skalierbarer Service.
- Ich lege auf AWS ein Lambda an, dass auf POST "air_shopping_requests" triggert und anhand der Daten eine "air_shopping_responses" Resource mit allem was dazu gehört anlegt.
- Generell sind alle WRITE Operationen noch bleeding edge features...

[EDIT]:

- In XapiX fehlt im Moment noch das to_many relationship feature, das brauchen wir hier

=> Ich werde einfach vorerst das Beispiel NDC XML einkürzen und nur einen Flug abfragen. Die Zeitintensive Umsetzung des to_many Features verschiebe ich auf nach dem Hackathon. Let's focus on WOW effects.

[/EDIT]:

Workflow:

"1." GET Requests auf relevante Resourcen, um das Anfrageformular zu bauen (airports, fares, routes, cities, etc., alles was man so brauch)
"2." Generiert eine UUID als ID für den air_shopping_request
"3.1" n x POST auf "/requested_flights" mit der generierten air_shopping_request_id
"3.2" n x POST auf "/requested_cabin_preferences" mit der generierten air_shopping_request_id
"3.3" POST auf "/air_shopping_requests" mit der generierten ID

Den 3. Schritt sollte man perspektivisch auch mit einem einzigen Bulk POST erledigen können. But for now it's OK...

"4." Das Lambda wird getriggert (air_shopping_request_id wird übergeben)
"5." Generiert eine UUID als ID für die "air_shopping_response"
"6.1" n x POST auf "/offered_flight_segements" mit der generierten air_shopping_response_id
"6.2" n x POST auf "/offered_fares" mit der generierten air_shopping_response_id
"6.3" POST auf "/air_shopping_responses" mit der generierten ID und air_shopping_request_id

Für das Demo Setup reicht es, wenn das Lambda Mock Daten an XapiX posted, das Lamda kann aber auch später durch eines ablösen, dass tatsächlich die Lufthansa API nutzt. Error handling ist noch so eine Frage, mal schauen. Für den ersten Prototypen reicht erstmal basic...

"7." Der Client kann die "air_shopping_response" als Compound Document abrufen mittels bspw. GET "/air_shopping_responses?filter[air_shopping_request_id]=123456-1234-1234-123456" (404 falls das Lambda noch nicht durch ist)

Bitte ausgiebig feedbacken! :)

**Comment by benway** [comment]
Good work, meister! Ist doch schon ein Einsatz.Frage: "das Lamda kann aber auch später durch eines ablösen, dass tatsächlich die Lufthansa API nutzt" -> wozu würde das Lambda die LH API nutzen?

**Comment by pickledolives** [comment]
Zur Ermittlung von Verfügbarkeit und Preis, die in die "air_shopping_response" einfließen

**Comment by pickledolives** [comment]
Ich komme mehr und mehr zu der Überzeugung, dass für den IATA Hackathon ein NDC XML Adapter notwendig sein wird, wenn wir ernst genommen werden wollen. Wir müssen einfach beweisen, dass XapiX NDC kompatibel ist.

Dazu muss der oben beschriebene Workflow erstmal stehen.

Dann würde ich ein rails-api Projekt aufsetzen, dass unser AirShopping NDC XML Beispiel parsen kann, aus den Daten wie oben beschrieben einen "air_shopping_requests" bastelt und dann so lange GET "air_shopping_responses" polled bis der Workflow s.o. durch ist und die Antwort im jsonapi Format da ist. Dann die Antwort noch nach NDC XML konvertieren, et voila!

**Comment by benway** [comment]
Flow für NDC THack case:

AS Request:
- origin
- destination
- cabin type (wo ich sitzen will)
- Personen: Kind, Adult

AS Response:
- Fluege mit
  - segments
  - price
- total price
-> alles gekapselt in einem offer mit id

OR Request:
- offer id
- contact data (email, name)
- payment info (credit card, paypal)

OR Response:
- Ergebnis (TrxProcessStatus)
  - hat booking geklappt
  - hat payment geklappt
  - booking code

**Comment by pickledolives** [comment]
Kategorie "vorbereitend zu erledigen" ist abgeschlossen. :-) Habe nun doch schon "to_many" Relationships drin. Den Arbeitstag den das heute gekostet hat war es definitiv wert und war zeitlich auch drin, dank des rapiden Fortschritts an der AWS-Lambda-Node-js-Front.

Danke, Christof, für den Flow oben,. Den kann ich nun schon angehen. :-)
